FEDERATION_SERVER="https://api.coins.asia/stellar/federate"
AUTH_SERVER="https://api.coins.asia/stellar/compliance"
SIGNING_KEY="GB4ZESJAJ7K5OQ5Y64PDZJS2KRFHJ36Q7BHOACHGDGSTUEZIDR3ZYUCJ"

[[CURRENCIES]]
code="PHP"
issuer="GBUQWP3BOUZX34TOND2QV7QQ7K7VJTG6VSE7WMLBTMDJLLAW7YKGU6EP"